# Required for Stellar ecosystem discovery
VERSION = "2.0.0"

# Your domain name (adjust if using custom domain)
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

# Your Stellar public key (signing key for SEP-1 and SEP-10)
SIGNING_KEY = "GCWAFMDZE27QHEM47NIO2WSYK6B6ZG3V4DRG6UGSSUPGC3LCXCHX6ZJ6"

# Optional: list other Stellar accounts associated with your domain
ACCOUNTS = [
    "GCWAFMDZE27QHEM47NIO2WSYK6B6ZG3V4DRG6UGSSUPGC3LCXCHX6ZJ6"
]

# Human-friendly organization info
[DOCUMENTATION]
ORG_NAME = "CogniTokens"
ORG_DBA = "CogniTokens"
ORG_URL = "https://cognitokens.com"
ORG_DESCRIPTION = "Building tokenized ecosystems on Stellar"
ORG_LOGO = "https://cognitokens.com/logo.png"
ORG_PHYSICAL_ADDRESS = "123 Token Lane, Crypto City"
ORG_OFFICIAL_EMAIL = "info@cognitokens.com"

# Currency details if issuing assets
[[CURRENCIES]]
code = "CGT"
issuer = "GCWAFMDZE27QHEM47NIO2WSYK6B6ZG3V4DRG6UGSSUPGC3LCXCHX6ZJ6"
display_decimals = 2
is_asset_anchored = false
name = "CogniToken"
desc = "Utility token for CogniTokens ecosystem"
conditions = "No conditions"
image = "https://cognitokens.com/cgt.png"
fixed_number = 100000000

# Optional: SEP-10 support (set your authentication server)
[WEB_AUTH_ENDPOINT]
URL = "https://api.cognitokens.com/auth"

# Optional: Transfer server for SEP-6 / SEP-24
[TRANSFER_SERVER]
URL = "https://api.cognitokens.com/sep6"

[TRANSFER_SERVER_SEP0024]
URL = "https://api.cognitokens.com/sep24"
