# Required for Stellar ecosystem discovery - mandatory
VERSION = "2.0.0"

# Your domain name (adjust if using custom domain)
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

# Your Stellar public key (signing key for SEP-1 and SEP-10)
SIGNING_KEY = "GBO2E4DQ6FKTN6Y2PHQK5AD3ZH3ROZAV2YVEOK4RLETBUOJ2EQOZSGKH"
